### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by BillKiller** [Harshiv-Patel/termux-jdkTools#1]
I did as recommanded to copy the java-tool to /usr/bin.However,termux reported that permission denied.WHy?I am a no-root phone user

**Comment by Harshiv-Patel** [comment]
it's not "/user/bin"   its "~/../user/bin" or "$PREFIX/bin", im kind of busy right now. So further help by Today evening

**Comment by Harshiv-Patel** [comment]
Does the tip given above solves your issue?

**Comment by Harshiv-Patel** [comment]
Does the tip given above solves your issue?
Did you try to add execute permission with `chmod` command ?
