### ISSUE TITLE
what is $jdk_tools

### ISSUE THREAD

**Issue by gMan1990** [Harshiv-Patel/termux-jdkTools#5]
`/data/data/com.termux/files/usr/bin/jdktools: line 16:  5060 Aborted                 dalvikvm -Xmx256M -cp $jdk_tools "$@"`

**Comment by Harshiv-Patel** [comment]
jdk-tools is a wrapper around the system's dalvik-vm command. So each and every tool doesn't have to include invocation of dalvik-vm, instead they all use this wrapper.

The execution flow becomes this :
> You call any of the tools from command line(step 1) --> they setup necessary argument/paths for the invocation of tool in the individual tool script/wrapper(step 2) --> individual tool's script/wrapper passes all user generated arguments as well as arguments generated in step 2 to the dalvik-vm residing in `/system/bin`. (final step)

Such as the wrapper, `jdk-tools` isn't ment to be called by user.

Please note that it's a setup not very well designed or prepared. It was meant to be used as experiment, until the official Open-JDK was available, that isn't available. And will be unlikely to ever. Further, internal changes in Android 8+ will probably render this setup useless, it should work on Android 5 and maybe Android 6/7.

the `javac` tool may be replaced by the `ecj` or `ecj-4.6` (for Android Lollipop) package from Official Termux repos.
Hope that satisfied all curiosity.
